### ISSUE TITLE
No File Requestor on Mac

### ISSUE THREAD

**Issue by intrepidsilence** [D4Delta/MamePlaylistBuilder#1]
When I run this app a requestor pops up with an okay button that instructs me to select my rom folder but after clicking okay a file requestor never appears.

**Comment by D4Delta** [comment]
I do not have any Mac to test on, so please test [this version](http://www.hamelin.gdn/test/MamePlaylistBuilder-1.0-OSXBUGFIX-UNTESTED.jar). If it work (or if it doesn't) tell me.

**Comment by intrepidsilence** [comment]
Ok, I am happy to test the new version.  Unfortunately the download link does not work:

Not Found

The requested URL /test/MamePlaylistBuilder-1.0-SNAPSHOT.jar was not found on this server.



Michael Spurlock
michael.spurlock@greyspaces.net

On May 9, 2017 at 11:58:09, D4Delta (notifications@github.com) wrote:

I do not have any Mac to test on, so please test this version. If it work (or if it doesn't) tell me.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/D4Delta/MamePlaylistBuilder","title":"D4Delta/MamePlaylistBuilder","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/D4Delta/MamePlaylistBuilder"}},"updates":{"snippets":[{"icon":"PERSON","message":"@D4Delta in #1: I do not have any Mac to test on, so please test [this version](http://www.hamelin.gdn/test/MamePlaylistBuilder-1.0-SNAPSHOT.jar). If it work (or if it doesn't) tell me.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/D4Delta/MamePlaylistBuilder/issues/1#issuecomment-3! 00210571"}}}

**Comment by D4Delta** [comment]
I've just fixed the link. Sorry for that.

**Comment by D4Delta** [comment]
[Here is the updated link](http://www.hamelin.gdn/test/MamePlaylistBuilder-1.0-OSXBUGFIX-UNTESTED.jar), because you seems to be using your e-mail to reply and thus can't get the updated link

**Comment by intrepidsilence** [comment]
This one works!  May I ask what you changed?


Michael Spurlock
michael.spurlock@greyspaces.net

On May 9, 2017 at 12:36:41, D4Delta (notifications@github.com) wrote:

(Here is the updated link)[http://www.hamelin.gdn/test/MamePlaylistBuilder-1.0-OSXBUGFIX-UNTESTED.jar], because you seems to be using your e-mail to reply and thus can't get the updated link

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/D4Delta/MamePlaylistBuilder","title":"D4Delta/MamePlaylistBuilder","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/D4Delta/MamePlaylistBuilder"}},"updates":{"snippets":[{"icon":"PERSON","message":"@D4Delta in #1: (Here is the updated link)[http://www.hamelin.gdn/test/MamePlaylistBuilder-1.0-OSXBUGFIX-UNTESTED.jar], because you seems to be using your e-mail to reply and thus can't get the updated link"}],"action":{"name":"View Issue","url":"https://github.com/D4Delta/MamePlaylistBuilder/issues/1#issuecomment-300224113"}}}

**Comment by intrepidsilence** [comment]
I don’t feel that my last reply was very clear.  Not only does the new link work allowing me to download the test version, the test version properly requested my rom dir and crated the lpl file!  

Thanks so much!

What did you change to make it ask for the directory?


Michael Spurlock
michael.spurlock@greyspaces.net

On May 9, 2017 at 12:36:41, D4Delta (notifications@github.com) wrote:

(Here is the updated link)[http://www.hamelin.gdn/test/MamePlaylistBuilder-1.0-OSXBUGFIX-UNTESTED.jar], because you seems to be using your e-mail to reply and thus can't get the updated link

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/D4Delta/MamePlaylistBuilder","title":"D4Delta/MamePlaylistBuilder","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/D4Delta/MamePlaylistBuilder"}},"updates":{"snippets":[{"icon":"PERSON","message":"@D4Delta in #1: (Here is the updated link)[http://www.hamelin.gdn/test/MamePlaylistBuilder-1.0-OSXBUGFIX-UNTESTED.jar], because you seems to be using your e-mail to reply and thus can't get the updated link"}],"action":{"name":"View Issue","url":"https://github.com/D4Delta/MamePlaylistBuilder/issues/1#issuecomment-300224113"}}}

**Comment by D4Delta** [comment]
Glad to hear that it does work ! I found [this](http://stackoverflow.com/questions/33599014/jfilechooser-not-showing) thread describing the exact same problem, I used EventQueue.invokeAndWait to execute the code, and it appears to be working.

**Comment by D4Delta** [comment]
I'm gonna close this issue, you can [see by yourself](https://github.com/D4Delta/MamePlaylistBuilder/commit/34fa063cf927e40a6077f4fd4f7cb3af9bb48f3d) the changes that have been done to solve the issue.
